name: ao3_scraper
description: "Provides a 'Fake API' for accessing info from Ao3, focused primarily on getting info from bookmarks and searching for Works in the site."
version: 1.0.3
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

repository: https://github.com/JooJASL/ao3-scraper-dart

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  html: ^0.15.0
  http: ^0.13.4
